version: '2'
services:
  chrome:
    image: selenium/node-chrome:4.0.0-rc-2-prerelease-20210907
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"
    links:
      - selenium-hub

  firefox:
    image: selenium/node-firefox:4.0.0-rc-2-prerelease-20210907
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6902:5900"
    links:
      - selenium-hub

  selenium-hub:
    image: selenium/hub:4.0.0-rc-2-prerelease-20210907
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"